name: ITPA
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _pytorch_select=0.2=gpu_0
  - blas=1.0=mkl
  - ca-certificates=2024.12.31=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cffi=1.15.1=py37h5eee18b_3
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.3.0=py37h54f3939_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.4=h6a678d5_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.7.16=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - backcall==0.2.0
      - cachetools==5.5.2
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpickle==2.2.1
      - cycler==0.11.0
      - dask==2022.2.0
      - dask-glm==0.3.2
      - dask-ml==2022.5.27
      - decorator==5.1.1
      - deepsnap==0.2.1
      - distributed==2022.2.0
      - fonttools==4.38.0
      - fsspec==2023.1.0
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - grpcio==1.62.3
      - heapdict==1.0.1
      - idna==3.10
      - importlib-metadata==6.7.0
      - ipdb==0.13.13
      - ipython==7.34.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - littleutils==0.2.2
      - llvmlite==0.39.1
      - locket==1.0.0
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - msgpack==1.0.5
      - multipledispatch==1.0.0
      - networkx==2.6.3
      - numba==0.56.4
      - numpy==1.21.6
      - oauthlib==3.2.2
      - ogb==1.3.6
      - outdated==0.2.2
      - packaging==24.0
      - pandas==1.3.5
      - parso==0.8.4
      - partd==1.4.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - prompt-toolkit==3.0.48
      - protobuf==3.20.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pygments==2.17.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - seaborn==0.12.2
      - sortedcontainers==2.4.0
      - sparse==0.13.0
      - tblib==2.0.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.1.0
      - tomli==2.0.1
      - toolz==0.12.1
      - torch==1.13.1+cu117
      - torch-cluster==1.6.1
      - torch-geometric==2.3.1
      - torch-scatter==2.1.1
      - torch-sparse==0.6.17
      - torch-spline-conv==1.2.2
      - torchvision==0.14.1+cu117
      - tornado==6.2
      - tqdm==4.67.1
      - traitlets==5.9.0
      - typing-extensions==4.7.1
      - urllib3==2.0.7
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - werkzeug==2.2.3
      - yacs==0.1.8
      - zict==2.2.0
      - zipp==3.15.0
prefix: /home/anonymous/anaconda3/envs/ITPA
